sudo: enabled
language: python
python:
 - "3.2"
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.5-dev" # 3.5 development branch
 - "3.6"
 - "3.6-dev" # 3.6 development branch
 - "3.7-dev" # 3.7 development branch
 # PyPy versions
 - "pypy3" # Pypy3 2.4.0
install: 
  #  - "sudo apt-get install pip3"
  - "sudo pip install -r requirements.txt"
  - "sudo apt-get install tshark"
  - "touch clickhouse.list"
  - "echo deb http://repo.yandex.ru/clickhouse/trusty stable main > clickhouse.list"
  - "sudo cp clickhouse.list /etc/apt/sources.list.d/clickhouse.list"
  - "sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E0C56BD4"
  - "sudo apt-get update"
  - "sudo apt-get install clickhouse-client clickhouse-server-common"
script: "sudo service clickhouse-server start"
script: "sudo ./setup.py"
script: ./systat.py
script: ./constat.py
