language: python
python:
 - "3.2"
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.5-dev" # 3.5 development branch
 - "3.6"
 - "3.6-dev" # 3.6 development branch
 - "3.7-dev" # 3.7 development branch
install: "pip install -r requirements.txt"
install: "sudo apt-get install tshark"
install: "cp .clickhouse.list /etc/apt/sources.list.d/clickhouse.list"
install: "sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E0C56BD4"
install: "sudo apt-get update"
install: "sudo apt-get install clickhouse-client clickhouse-server-common"
script: systat
script: constat
