sudo: enabled
language: python
python:
 - "3.2"
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.5-dev" # 3.5 development branch
 - "3.6"
 - "3.6-dev" # 3.6 development branch
 - "3.7-dev" # 3.7 development branch
install:
  - "sudo apt-get install python3-pip"
  #- "sudo pip install -r requirements.txt"
  - "sudo pip3 install -r requirements.txt"
  - "sudo apt-get install tshark"
  - "sudo mkdir /etc/systemd"
  - "sudo mkdir /etc/systemd/system"
  - "sudo ./setup.py"
before_install:
  - docker pull yandex/clickhouse-server
  - docker run -d -p 127.0.0.1:8123:8123 --name some-clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server:1.1.54159
  - docker ps -a
script: 
  - pytest
  #- python3 -m pytest iocwatch.py
  #- python3 -m pytest systat.py
  #- python3 -m pytest constat.py
  #- python3 -m pytest setup.py
  #- python3 -m pytest otxget.py