# Politraf config
interface: tun0
# tshark filter
# TCP 1-1024 and UDP 53
#bpf_filter: 'tcp dst portrange 1-1024 or udp dst port 53'
# From private
bpf_filter: 'src net 192.168.0.0/24'
#
# AlienVault open threat exchange API key
otx_key: 
