# Politraf config
interface: tun0
# tshark filter
# Light TCP 1-1024 and UDP 53
#bpf_filter: 'tcp dst portrange 1-1024 or udp dst port 53'
# Medium TCP AND UDP
bpf_filter: 'tcp or udp'
#
# AlienVault open threat exchange API key
otx_key: 
