##############################################################################
# Politraf config
##############################################################################
#
# Clickhouse
#
db_url: "http://127.0.0.1:8123/"
username: default
password:
##############################################################################
#
# Promiscuous interfaces
#
#interface: tun0,eth0
interface: tun0
##############################################################################
#
# Tshark filter
#
# Light TCP 1-1024 and UDP 53
#bpf_filter: 'tcp dst portrange 1-1024 or udp dst port 53'
# Medium TCP AND UDP
bpf_filter: 'src net 10.8.0.0/24 and not host 10.8.0.1'
##############################################################################
# AlienVault open threat exchange API key
#
otx_key:  
##############################################################################
# Censys key
#
#CAPI_URL:
CUID:
CSECRET:
##############################################################################
# Setup PUBLIC subnet to scan (CIDR)
#
SUBNET: 185.46.11.0/24
# Time zone
#
time_zone: Europe/Moscow
##############################################################################
ioc_file: /opt/politraf/self_ioc_list.csv
traf_file: /opt/politraf/current/traff.csv
